theme: jekyll-theme-slate
title: HotWax Commerce | Open Source Projects
description: >-
  Open source projects by HotWax Commerce — the omnichannel Order Management
  System that provides retailers the best return on their inventory with
  solutions such as Buy Online Pick-Up In Store, Ship From Store & Pre-Orders.
